### ISSUE TITLE
Feature request: Delete everything in specify storage folder

### ISSUE THREAD

**Issue by stickman0131** [Feline-Studio/myback-devtools#12]
A function that looks like this
```
deleteEverything(dir? : string){
  //delete every thing in dir
  //if dir is undefined, then delete the default folder
}
```

**Comment by daviddaytw** [comment]
The server side had implemented file recursive deletions: https://github.com/Skiesoft/MyBack/commit/13915de25dbd5a3e2790bf06800d93d0af00911f

The SDK should be updated very soon.

**Comment by daviddaytw** [comment]
It is added in [v0.6.3](https://github.com/Skiesoft/myback-devtools/compare/v0.6.2...v0.6.3).
Please update your local SDK version.
